theme: jekyll-theme-minimal
title: [Serdar Helli]
subtitle: [Serdar Helli]
author: Selahattin Serdar Helli
description: I am Serdar Helli. This is my blog
logo: /assets/images/logo.png
twitter_user: epitaph145
simple_search: https://www.google.com/search

header_navigation:
  - title: Home
    url: /index.md

  - title: CoreNeuroArt
    url: /CoreNeuroArt.md

