theme: jekyll-theme-minimal
title: [Serdar Helli]
description: [ I am Serdar Helli. This is my blog]
logo: [SerdarHelli.github.io/assets/images/logo.png]
email: [s.serdarhelli@gmail.com]
timezone: [Turkey/Istanbul]
