theme: jekyll-theme-minimal
title: [Serdar Helli]
subtitle: [Serdar Helli]
author: Selahattin Serdar Helli
description: I am Serdar Helli. This is my blog
logo: SerdarHelli.github.io/assets/images/logo.png
twitter_user: epitaph145
simple_search: https://www.google.com/search
